// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjK-8pS5vrnK6JFSH7Us11JRgnFRl8wJc',
    appId: '1:369902018158:web:2b3711336d2ca7ac7c907f',
    messagingSenderId: '369902018158',
    projectId: 'constructos2026',
    authDomain: 'constructos2026.firebaseapp.com',
    storageBucket: 'constructos2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWaTjN3OG_FRdtXm2ZMBHA5146TAWc2KY',
    appId: '1:369902018158:android:b6c4cff7583044717c907f',
    messagingSenderId: '369902018158',
    projectId: 'constructos2026',
    storageBucket: 'constructos2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBB7Nrkc-Ua4Af6c30TkMYyhOdIifncvU',
    appId: '1:369902018158:ios:abefe872825133177c907f',
    messagingSenderId: '369902018158',
    projectId: 'constructos2026',
    storageBucket: 'constructos2026.firebasestorage.app',
    iosBundleId: 'com.example.letschat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBB7Nrkc-Ua4Af6c30TkMYyhOdIifncvU',
    appId: '1:369902018158:ios:abefe872825133177c907f',
    messagingSenderId: '369902018158',
    projectId: 'constructos2026',
    storageBucket: 'constructos2026.firebasestorage.app',
    iosBundleId: 'com.example.letschat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjK-8pS5vrnK6JFSH7Us11JRgnFRl8wJc',
    appId: '1:369902018158:web:0be04d835b2b13827c907f',
    messagingSenderId: '369902018158',
    projectId: 'constructos2026',
    authDomain: 'constructos2026.firebaseapp.com',
    storageBucket: 'constructos2026.firebasestorage.app',
  );
}
